### ISSUE TITLE
[Suggestion] getPokemonsByFamily()

### ISSUE THREAD

**Issue by khitas** [NicklasWallgren/PokemonGoAPI-PHP#103]
Can you please add a method "getPokemonsByFamily()" similar to "getPokemonsByType()" to collect all Pokemon from the same family ?

Thanks in advance

**Comment by NicklasWallgren** [comment]
https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/310b338f014616c1c53c2b9001aa335f8bfe58c3
