### ISSUE TITLE
Use without composer

### ISSUE THREAD

**Issue by pedrosodre** [NicklasWallgren/PokemonGoAPI-PHP#104]
Hi,

is any way to use it with PHP without composer?

**Comment by Ni42** [comment]
The question is: why not use composer? If you can't install it on a production server, just copy all the required files over from your local install and you don't need to run it there.

**Comment by pedrosodre** [comment]
I want run it just with cURL and a simple php framework like codeigniter. Just want to do a small thing.

**Comment by Ni42** [comment]
Can't really help you with that then... composer installs are the de-facto standard for PHP right now for some time. It's not really a big library, and it works on all OSes, so just go and get it.

**Comment by NicklasWallgren** [comment]
Composer is the way to go. Closing this.
