### ISSUE TITLE
Empty Response 

### ISSUE THREAD

**Issue by curt2008** [NicklasWallgren/PokemonGoAPI-PHP#11]
After login is successful I'm getting a complete empty array from this function? 

`$inventory = $pokemonGoApi->getInventory();`

You got any contact information? Skype?

**Comment by NicklasWallgren** [comment]
Take a look at the examples inside the example folder.

```
 // Retrieve the inventory
 $inventory = $pokemonGoApi->getInventory();

// Retrieve the poke bank
 $pokeBank = $inventory->**getItems()**->getPokeBank();

// Retrieve a pokemon of type pidgey
$pokemon = current($pokeBank->getPokemonsByType(PokemonId::PIDGEY));
```

You can reach me at nicklas.wallgren@gmail.com
