### ISSUE TITLE
Error during getStats 

### ISSUE THREAD

**Issue by Raphaelbm** [NicklasWallgren/PokemonGoAPI-PHP#110]
Hello !

I don't know why but I have this error with my PTC account (test account):

`Warning: get_resource_type() expects parameter 1 to be resource, null given in /home/pokedev/pokemon-dev/api/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php on line 54
fp must be a string or file resource`

I think this line of my code make that error:

`$playerStats = $inventory->getItems()->getStats();`

I made the same test with an other PTC account and a Google account and that works perfectly !

Thanks you again ^^

**Comment by Raphaelbm** [comment]
I don't know but all examples don't work... I think it's why I made a `git pull`

**Comment by NicklasWallgren** [comment]
@Raphaelbm The account is probably banned, I'll add a check for this at some point.

**Comment by Raphaelbm** [comment]
@NicklasWallgren Ok, I can't play with this account... But there is a message like "Problem with the server..."

**Comment by f2008305** [comment]
that account is banned. it happened also to a my test account.

**Comment by NicklasWallgren** [comment]
Resolved.
