### ISSUE TITLE
[Suggestion] Default environment variables file path

### ISSUE THREAD

**Issue by WisdomSky** [NicklasWallgren/PokemonGoAPI-PHP#111]
In [`Kernel.php`](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/blob/master/src/Kernels/Kernel.php#L45), you can pass an argument to the constructor for a custom environment variables file path, but there is no default path specified.

This means that the library doesn't utilize the environment variables by default, and you need to pass it(the path to the file) to the `ApplicationKernel` constructor everytime you want to use the environment variables.

It somehow causes confusion to other people who didn't know this, since in most other projects which also uses phpdotenv, the common implementation is the environment file is loaded by default, anyone just need to create a `.env` and they're ready to add/change environment variables anytime without any extra configuration to make it work.

My suggestion is to specify a default location for the .env file. 
I prefer the base directory (_from Kernels directory, it would be_ **'../../'**) since the `.env.example` file is there and commonly users just copy this file on the same location while removing the `.example` on the filename.

Common user impression is the user will think that it is the default location since it is there and he will think that if he renames it to `.env`, it will start to work.

The **Kernel#loadEnvironmentVariables()** method may look like this (pseudo-code):

```php
    protected function loadEnvironmentVariables()
    {
        $defaultEnvironmentFilePath = '../../';

        // Check if the environment file path is defined
        if ($this->environmentFilePath === null) {
            // check the default location instead
            if (file_exists($defaultEnvironmentFilePath)) {
                $this->environmentFilePath =  realpath($defaultEnvironmentFilePath);
            } else {
                return;
            }
        }
        // Initialize the environment instance
        $dotenv = new Dotenv($this->environmentFilePath);
        // Load environment file in given directory.
        $dotenv->load();
    }
```

**Comment by WisdomSky** [comment]
I think the opposite is much easier and much straight forward. We will not directly require the .env file, but once the library detects that an .env file exists on the default location, the library should load it. 

This will make instantiating ApplicationKernel with environment variables much easier since the user will not need to provide a custom path to where the .env file resides as long as an .env file is created at the default location. It will be cumbersome to provide the path everytime the user creates an ApplicationKernel object.

The implementation is really confusing, but still it is just a minor debatable issue.

**Comment by Ni42** [comment]
Sure, it's fine if there's default values coming from the environment, but it's inconsistent to allow passing some parameters by value, and the others only indirectly. Just like I'd love to be able to pass my own Monolog instance that goes to php://output (for CLI), but that's not a writeable path, and doesn't have a directory, so I can't use that either. :)

**Comment by DrDelay** [comment]
I gotta admit, when I first wanted to use the *.env*-file I spent a good 20 minutes until I figured out that I had to do more than `cp .env.example .env` (specify the path). It is confusing.

Also, for things like the proxy setting it does make some sense that it is "hardcoded" in the config file, because it shouldn't change. Usernames/passwords on the other hand can be provided by a client.

I'm totally with @Ni42 regarding the logger, you should just be able to pass your PSR-3 compliant instance.

**Comment by WisdomSky** [comment]
> I gotta admit, when I first wanted to use the .env-file I spent a good 20 minutes until I figured out that I had to do more than cp .env.example .env (specify the path). It is confusing.

Same thing actually happened to me too. :smile: 
I wouldn't figure out how to make it work without tracing the code.

IMHO, having documentation would be really helpful.

**Comment by NicklasWallgren** [comment]
I have added the ability to pass a custom PSR-3 compliant logger instance.

**Comment by NicklasWallgren** [comment]
@WisdomSky Feel free to write one ;)

**Comment by NicklasWallgren** [comment]
The environment variables has been removed. Thanks for the input.

Resolved.
