### ISSUE TITLE
API requirement

### ISSUE THREAD

**Issue by plonk5638** [NicklasWallgren/PokemonGoAPI-PHP#112]
hi,

im a PHP programmer since 5 years ago, but new in github (just learn about git and composer about 2 days ago)

i very struggle here to run this API, its around 2-3 hours but always cant work.
i download XAMPP 32bit PHP 7 >> get error (i forgot what the error messege)
ok i download XAMPP 32bit PHP 5.5 >> get error your php 5.5, minimun req >= 5,6
ok i download XAMPP 32bit PHP 5.6 >> composer install success, then try examples script but getting error: sry we only supp PHP 64bit

i search XAMPP 64bit windows but it doesnt exists yet.
so i try WAMPP 64bit PHP 5.6-7.0 >> error : we only support php 64bit
WTF. i install wampserver3.0.4_x64_apache2.4.18_mysql5.7.11_php5.6.19-7.0.4.exe but he said i dont use 64bit >.<

i try to install in my VPS , ubuntu 14 64bit >> error your php is 5.5

before i go too far to uninstall - reinstall something,  i try to ask a question here.
can you give me a clue to run this API? i prefer windows.

ty. im very appreciate your help
sry for my english and my bad knowledge

**Comment by WisdomSky** [comment]
> so i try WAMPP 64bit PHP 5.6-7.0 >> error : cmd didnt recognize "php" command. my be wampp have another setting to use PHP CLI that i dont know.

Hi!

This problem is not really related to PokemonGoAPI.

But can you try following this walkthrough tutorial?

Your problem is that php is not recognized by your command prompt because it's not loaded in the environment variables, so to make it work, you need to add php to the environment variables path on your windows.

[https://john-dugan.com/add-php-windows-path-variable/](https://john-dugan.com/add-php-windows-path-variable/)

**Comment by plonk5638** [comment]
yes i absolutly know my question is not related to PogoAPI
but i dont know where i can get help.
no discord here.

i try search solution in stackoverflow which is offer the same solution with you.
but i get >> error : we only support php 64bit
WTF. i install wampserver3.0.4_x64_apache2.4.18_mysql5.7.11_php5.6.19-7.0.4.exe but he said i dont use 64bit >.<

----------
i will explain my cronological/walkthrough how i run this API

i download PHP standalone so i wont use XAMPP/WAMPP anymore, i download http://windows.php.net/downloads/releases/php-5.6.24-nts-Win32-VC11-x64.zip , then extract to c:\php

c:\php > mkdir pogoapi
c:\php > cd pogoapi
create file composer.json and paste this code:
{"minimum-stability": "dev",
"prefer-stable": true}

go to cmd and type : composer require nicklasw/pkm-go-api
c:\php\pogoapi > composer require nicklasw/pkm-go-api
result : 
blablabla..........
Writing lock file
Generating autoload files

(i think that means install via composer success)

i copy folder examples from C:\php\pogoAPI\vendor\nicklasw\pkm-go-api\examples to C:\php\pogoAPI\examples
cd C:\php\pogoAPI\examples
C:\php\pogoAPI\examples>php RetrievePlayerProfileExample.php
For now we only support PHP on 64bit platforms \n

-----
i am pretty sure i use PHP 5.6 64bit.

my OS : windows 7 ultimate SP1 64bit
PHP standalone : http://windows.php.net/downloads/releases/php-5.6.24-nts-Win32-VC11-x64.zip
wampp : wampserver3.0.4_x64_apache2.4.18_mysql5.7.11_php5.6.19-7.0.4.exe

and i check with below script , i called check.php
<?php 
echo "PROCESSOR_ARCHITECTURE => " . $_SERVER["PROCESSOR_ARCHITECTURE"]."\n"; 
echo "PROCESSOR_IDENTIFIER => " . $_SERVER["PROCESSOR_IDENTIFIER"]."\n"; 
echo "PROCESSOR_LEVEL => " . $_SERVER["PROCESSOR_LEVEL"]."\n"; 
echo "PROCESSOR_REVISION => ". $_SERVER["PROCESSOR_REVISION"]; 
?>

c:\php\pogoAPI>php a.php
PROCESSOR_ARCHITECTURE => AMD64
PROCESSOR_IDENTIFIER => Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL => 6
PROCESSOR_REVISION => 3a09

then run
c:\php\pogoAPI\examples>php RetrievePlayerProfileExample.php

result:
For now we only support PHP on 64bit platforms \n

OMG , i got headache now, >.<

NOTE: i uninstall WAMPP and XAMPP before

**Comment by Ni42** [comment]
What does `echo PHP_INIT_SIZE;` say?

Can you try using the newest x64 PHP7 version instead? The PHP5 64bit Windows builds are still marked as "experimental".

**Comment by DragonStar01** [comment]
i have  the same prob :/ 
Downloaded wamp64 bit but when i try to this code 

```php
switch(PHP_INT_SIZE) {
    case 4:
        echo '32-bit version of PHP';
        break;
    case 8:
        echo '64-bit version of PHP';
        break;
    default:
        echo 'PHP_INT_SIZE is ' . PHP_INT_SIZE;
}
```
it sows
```
 C:\wamp64\www\NicklasWallgren\examples>php All.php
32-bit version of PHP
C:\wamp64\www\NicklasWallgren\examples>php -v
PHP 7.0.8 (cli) (built: Jun 21 2016 15:27:20) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by Ni42** [comment]
@DragonStar01 You need to install the PHP x64 build from windows.php.net, or it won't work. Technically it's as easy as overwriting the directory, but I have no idea about Wamp.

**Comment by plonk5638** [comment]
i try now.
--this post will updated--

**Comment by NicklasWallgren** [comment]
Resolved.

**Comment by DrDelay** [comment]
This "trail-and-error" log could actually help some Windows users. Some more formatting and this could be in the wiki.

**Comment by Ni42** [comment]
@plonk5638 Happy to help ;)
If you want to ping someone, place @ in front of their name, you even get autocompletion for that here.

Maybe we should really write a little document on the requirements/environment setup. It seems like there is a PHP7 req on Windows at least.

**Comment by plonk5638** [comment]
@Ni42 
thanks.
for this clue -> @
