### ISSUE TITLE
profileData error

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#113]
I downloaded the last release and now I can't get the player profile data.
Since last week, everything ok. Now I get this error

![immagine](https://cloud.githubusercontent.com/assets/15869726/17692091/4a9f42c2-6398-11e6-9290-58f884216e7e.png)

**Comment by f2008305** [comment]
me too.
$profileData = $pokemonGoApi->getProfile()->getProfileData();
it gives error because $pokemonGoApi->getProfile() give empty result

**Comment by Raphaelbm** [comment]
Yes, same problem !

**Comment by NicklasWallgren** [comment]
The `getProfileData()` method has been deprecated and removed. 

Use getData() instead, or access the profile data directly.

**Comment by NicklasWallgren** [comment]
I'll will update the example.

**Comment by NicklasWallgren** [comment]
Have a look at the RetrievePlayerProfileExample example.

Resolved.
