### ISSUE TITLE
evolve and proxy

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#114]
2 requests in one:
1) is there a way to evolve a pokemon? in example i don't see it
2) is there a way to set a proxy or more? (to avoid getting your real ip from niantic and balance requests)

**Comment by paoloalby** [comment]
yes, $pokemon->evolve()

but check canEvolve() first.

**Comment by WisdomSky** [comment]
what do you mean by setting proxy or more? hiding behind multiple level of proxies?

**Comment by f2008305** [comment]
i mean this:
your server => niantic server
your server => proxy server => niantic server
so if they will ever ban your ip you can simply change the proxy and continue...
if you have100 users logging in through your server it will be easy to get banned from niantic if they start to do it...

**Comment by NicklasWallgren** [comment]
It's possible to send the traffic via a proxy.

https://github.com/NicklasWallgren/PokemonGoAPI-PHP/pull/83
