### ISSUE TITLE
canUpgrade, canEvolve, canRemove refine

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#115]
Add these checks in following methods.

canRemove:
- check if a pokemon is not assiged to a Gym. Else, you can't remove it

canUpgrade:
- check if a pokemon is not assiged to a Gym. Else, you can't upgrade it
- check that the pokemon LEVEL is not greater than trainer LEVEL. Else, you can't upgrade more

canEvolve:
- check if a pokemon is not assiged to a Gym. Else, you can't evolve it

**Comment by Cucciruru** [comment]
hi all
when i use the site that use your API i can Upgrade my pokemon 0.5 more then the game.
i put here some images for example:

i'm level 24.
in this two image i had upgrade my pokemon in the game and i can't upgrade more.
![1](https://cloud.githubusercontent.com/assets/10656691/17730525/4f0b56f8-6469-11e6-93fa-37a6222165a3.jpg)
![2](https://cloud.githubusercontent.com/assets/10656691/17730527/4f1224c4-6469-11e6-8ed1-c8f8719290a8.jpg)

but here, in the site, i Upgrade the pokemon and it become from 25.5 to 26(no more)
![3](https://cloud.githubusercontent.com/assets/10656691/17730528/4f12bec0-6469-11e6-9221-520abb94f7e7.jpg)
![4](https://cloud.githubusercontent.com/assets/10656691/17730526/4f118bfe-6469-11e6-858b-3cc293d4ceaa.jpg)

so, in the site we can upgrade 0.5 more.

**Comment by f2008305** [comment]
does it means that exists the code $pokemon->upgrade() ???

**Comment by NicklasWallgren** [comment]
I have started refining the methods, a few thing left thought.

https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/df3ce17b15801ea5aefdda1d701a623f2c337fdc

**Comment by NicklasWallgren** [comment]
Resolved.
