### ISSUE TITLE
[WARNING] Niantic ban !

### ISSUE THREAD

**Issue by Raphaelbm** [NicklasWallgren/PokemonGoAPI-PHP#116]
Hello !

Niantic starts ban account people who logging in third-party application !

I don't know if they are able to ban Google account, but since this morning many PTC account are banned.

https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by NicklasWallgren** [comment]
Not a issue, thanks for the notice anyway.

**Comment by Raphaelbm** [comment]
Yep sorry ^^
