### ISSUE TITLE
how to set device idendity

### ISSUE THREAD

**Issue by plonk5638** [NicklasWallgren/PokemonGoAPI-PHP#118]
hi,

today, niantics broadcast permanent banned email for people who play pokemon from 3rd party.

lets imagine i build web like pokeadviser.com for myself only in localhost (not for bot purpose but only for viewing stat more efficient). Thats must be called 3rd party, isnt?
**so, its possible for niantic to ban my account which login in my website.**

---

due this issue, i wanna ask:
1. **how to not get ban when we use this API?** (not 100% safe, but maybe we can decrease ban possibility with some configuration)
2. **how to set device idendity with this API?** i open every single file in this API but cant find file that set device idendity, like : device ID, android boardname, device model (Galaxy note 5), device brand (samsung), firmware , etc. Because i think with this setting we can go more safely.

[sry for my english.]

**Comment by f2008305** [comment]
me too...
i was currently using my own site to view my data...
but from 2 days i'm only accessing a  fake account to test if they really ban it. until now not yet. but never say never

**Comment by Ni42** [comment]
Filling in the Signature, and then request signing isn't implemented here yet, you will have to wait until that works. Although even if that is implemented, the API will never be fully able to replicate the game and be detectable.

**Comment by plonk5638** [comment]
@Ni42 it's fine if not implemented yet.
just dont close this thread before signature feature implemented in this API
