### ISSUE TITLE
Always have an issue on 'use' keyword

### ISSUE THREAD

**Issue by ajdev2016** [NicklasWallgren/PokemonGoAPI-PHP#12]
example:

require __DIR__ . '/../vendor/autoload.php';
use NicklasW\PkmGoApi\Authenticators\Factory;
use NicklasW\PkmGoApi\Kernels\ApplicationKernel;
use POGOProtos\Enums\PokemonId;

** what does it mean?

**Comment by NicklasWallgren** [comment]
Read up on "PHP namespaces".
