### ISSUE TITLE
pokemon moves

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#120]
could create or upload an example of file to get all possible moves of a pokemon by id?
we can simply get id of the 2 moves of a pokemon but what i'm searching are the names of all possible moves for a pokemon.
i saw there is a file with all details but how to grab that info using a function?
i tried various ways but failed
PokemonGoAPI-PHP/src/Api/Pokemon/Data/PokemonMetaRegistry.php

**Comment by DrDelay** [comment]
See #121

**Comment by NicklasWallgren** [comment]
```
// Retrieve the pokemon metadata
$data = PokemonMetaRegistry::getByPokemonId('INSERT_POKEMON_ID');

$data->getQuickMoves();
$data->getCinematicMoves();
```

**Comment by NicklasWallgren** [comment]
Resolved.

**Comment by f2008305** [comment]
sorry but i did that but the result is empty.
the quickmoves and cinematicmoves are empty results (always)
i put at start naturally use NicklasW\PkmGoApi\Api\Pokemon\Data\PokemonMetaRegistry;
am i missing something else? or is it an error of coding?

**Comment by DrDelay** [comment]
See #123, you probably didn't update (`composer update` / `git fetch origin && git pull` / `git fetch upstream/master && git merge upstream/master`).
