### ISSUE TITLE
Question about BAN

### ISSUE THREAD

**Issue by milowei** [NicklasWallgren/PokemonGoAPI-PHP#122]
If we use this api login, the lat and lang all 0. Do you think that will make Niantic think we are Use of any other third-party software or app and make our account get soft ban or terminated?

**Comment by Ni42** [comment]
It's detectable, and whether they ban you or not it at their discretion. I would think they have other ban targets in mind, as long as you don't really bot using this, but you can never be sure, and they would be in the right if they did so.

**Comment by plonk5638** [comment]
hmm.. i see
