### ISSUE TITLE
pokemon moves

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#123]
sorry but i did that but the result is empty.
the quickmoves and cinematicmoves are empty results (always)
i put at start naturally use NicklasW\PkmGoApi\Api\Pokemon\Data\PokemonMetaRegistry;
am i missing something else? or is it an error of coding?
http://prntscr.com/c7x77z <- screenshot of that array
you closed the issues before checking if it was really solved. sorry for reopening a new one.

**Comment by DrDelay** [comment]
I just checked it again, it works. You should make sure that you are on the latest version.

``` php
use NicklasW\PkmGoApi\Api\Pokemon\Data\PokemonMetaRegistry;

$abra = PokemonMetaRegistry::getByPokemonId(\POGOProtos\Enums\PokemonId::ABRA);
dump($abra);
dump($abra->getQuickMoves()->getMovesStrings());
```
![PokemonMoveMetaOutput](https://cloud.githubusercontent.com/assets/15216003/17829830/090ee756-66bb-11e6-8bb4-c6637a3fab2f.png)
