### ISSUE TITLE
error of last composer update

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#124]
Fatal error: Class 'Illuminate\Support\Collection' not found in /var/www/pokemongo/private/vendor/nicklasw/pkm-go-api/src/Api/Pokemon/Collection/PokemonCollection.php on line 8

**Comment by f2008305** [comment]
now that fatal error seems solved but there is a new one...
Warning: get_resource_type() expects parameter 1 to be resource, null given in /**********/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php on line 54

**Comment by f2008305** [comment]
am i the only one to get that error? it is a warning error but don't allow me to get all data...
probably i will downgrade the versione until it will be fixed xd

**Comment by NicklasWallgren** [comment]
I can't reproduced the problem. Have you updated the dependencies?
