### ISSUE TITLE
$inventory = $pokemonGoApi->getInventory();

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#125]
$inventory = $pokemonGoApi->getInventory();
this function is not working anymore...
probably some update on niantic side...

**Comment by NicklasWallgren** [comment]
Is the account banned?

**Comment by f2008305** [comment]
no it's not. i tested on other account and same.
moreover i can get correctly $profileData = $pokemonGoApi->getProfile()->getData();
but not the getInventory() and this cause the error...

**Comment by f2008305** [comment]
now on all other accounts i get this:
Fatal error: Class 'Illuminate\Support\Collection' not found in /var/www/pk/private/vendor/nicklasw/pkm-go-api/src/Api/Pokemon/Collection/PokemonCollection.php on line 8

**Comment by NicklasWallgren** [comment]
See DrDelay answer in https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/120.
