### ISSUE TITLE
canEvolve again not working after update

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#130]
edit: also pkm->evolve() not work anymore.

**Comment by DrDelay** [comment]
You'd be more specific with your bug reports.

"Not work" can be anything from a wrong result over an Exception being thrown or a fatal error up to a segfault.

**Comment by f2008305** [comment]
no errors. just they don't make their work no more.
the canEvolve() always give false/0
the evolve() simply don't evolve the pokemon.
just test yourself to evolve a pidgey and see?

**Comment by NicklasWallgren** [comment]
Who needs unit tests? ;)

https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/96076b57d7886970444397fb7b1d5af20ee6fe17

**Comment by f2008305** [comment]
Sorry to say it but still not work

**Comment by f2008305** [comment]
Currently i tested only canEvolve. I will try evolve asap

**Comment by f2008305** [comment]
fixed
