### ISSUE TITLE
Login with google API

### ISSUE THREAD

**Issue by vntopcoders** [NicklasWallgren/PokemonGoAPI-PHP#138]
I try to integrate Google API to login to my system, sometimes its works, but sometimes we got the error:
`
2016/08/28 04:36:12 [error] 3875#0: *431 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined property: stdClass::$id_token in /usr/share/nginx/html/poke/src/Authentication/Managers/Google/AuthenticationCode/Parsers/OauthTokenParser.php on line 44
PHP message: PHP Notice:  Undefined property: stdClass::$expires_in in /usr/share/nginx/html/poke/src/Authentication/Managers/Google/AuthenticationCode/Parsers/OauthTokenParser.php on line 45
PHP message: PHP Notice:  Undefined property: stdClass::$refresh_token in /usr/share/nginx/html/poke/src/Authentication/Managers/Google/AuthenticationCode/Parsers/OauthTokenParser.php on line 46"
`

**Comment by DrDelay** [comment]
You'd have to provide some of your code, I think the problem lies in there rather than this API; like you passing something invalid instead of a proper AccessToken to `Factory::create`.
