### ISSUE TITLE
Wrong code in examples/GUI_BestCpPokemonDetails.php

### ISSUE THREAD

**Issue by Raphaelbm** [NicklasWallgren/PokemonGoAPI-PHP#140]
I tested this examples because my code doesn't work now : examples/GUI_BestCpPokemonDetails.php

But this line is wrong:

`$pokez = $pokemonGoApi->getInventory()->getItems()->getPokeBank()->getPokemons();`

Solution:

`$pokez = $pokemonGoApi->getInventory()->getPokeBank()->getPokemons();`

getPokeBan() function is in inventory I think.

**Comment by DrDelay** [comment]
Thanks for reporting, I fixed it along with some other adjustments.
