### ISSUE TITLE
[Help Wanted] Pokemon Moves

### ISSUE THREAD

**Issue by TacoBytes** [NicklasWallgren/PokemonGoAPI-PHP#146]
When retrieving a user's pokemon collection, the array returns integers and it use to return a string (for example 'move1' and 'move2' use to return a value like 'THUNDER_SHOCK_FAST' and 'DISCHARGE'). Is there a quick way to get a list of moves with the integer value assigned to it (I am assuming it is an ID associated with a string) being returned?

**Comment by DrDelay** [comment]
There are Enum classes for what you are looking for:

* [raw protos](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Enums/PokemonMove.proto)
* [compiled with bramp/protoc-gen-php](https://github.com/NicklasWallgren/pogoprotos-php/blob/master/src/POGOProtos/Enums/PokemonMove.php)
* [compiled with protobuf-php](https://github.com/jaspervdm/pogoprotos-php/blob/master/src/POGOProtos/Enums/PokemonMove.php)

The second (bramp) is the one used in this project.

**Comment by TacoBytes** [comment]
@Drdelay thank you.
