### ISSUE TITLE
Can't login to app

### ISSUE THREAD

**Issue by HadesD** [NicklasWallgren/PokemonGoAPI-PHP#147]
Today I 've trying to login, but it return the error code like this:

```
Exception in PokemonData.php line 63:
Incorrect wire format for field 1, expected: 1 got: 2
```

**Comment by Raphaelbm** [comment]
Your code maybe ? ^^

**Comment by sedziwoj** [comment]
I think is same problem with google auth #142

**Comment by Vlakon** [comment]
I get approximately the same error. Only one of my user tho, both with token and user/pass. It has worked for a long time, with no changes to the code.

Incorrect wire format for field 1, expected: 1 got: 0

**Comment by DrDelay** [comment]
Same problem as #142.
