### ISSUE TITLE
Google Login Api

### ISSUE THREAD

**Issue by Callosino96** [NicklasWallgren/PokemonGoAPI-PHP#148]
I'm trying to connect with Google Email and Password, or Google Ticket, but i can't do it.
With PTC works done.

Gyazo of my error: https://gyazo.com/e13b58f8f33cd125c0f1254977af8d94

Thanks.

**Comment by DrDelay** [comment]
A lot of issues regarding *PokemonData* have been resolved, you may check out #142 for details.

Can you pull the latest changes and `composer update` and try again?
