### ISSUE TITLE
GetMapResources() return empty object

### ISSUE THREAD

**Issue by gabrieltva** [NicklasWallgren/PokemonGoAPI-PHP#149]
Hi guys, 

I am trying to return the pokemon/pokestop nearby of the location, but the method GetMapResources() return a empty object, like this:
`object(NicklasW\PkmGoApi\Api\Map\Data\Resource)#45 (6) { ["pokestops":protected]=> array(0) { } ["gyms":protected]=> array(0) { } ["spawnPoints":protected]=> array(0) { } ["catchablePokemons":protected]=> array(0) { } ["wildPokemons":protected]=> array(0) { } ["nearbyPokemons":protected]=> array(0) { } }
`

Searching about this, in another API (python), it is necessary add a file named "encrypt.so" to search pokemons. In this API it is necessary too?

**Comment by Vankxr** [comment]
Tell us what are you sending as request message

**Comment by gabrieltva** [comment]
How I can do that? @Vankxr

**Comment by DrDelay** [comment]
Request signing is not implemented here, yet. #92 has been around for some time, though.

**Comment by Vankxr** [comment]
Dump the request after building and before sending it to the server ? @gabrieltva

**Comment by Ni42** [comment]
That won't help, because in order to get map objects, you need to sign your request, which this API can't currently do, see DrDelays comment.
