### ISSUE TITLE
Uncaught Exception: Retrieved a unknown status code 52 

### ISSUE THREAD

**Issue by sensityy** [NicklasWallgren/PokemonGoAPI-PHP#16]
Hello again.. Not sure what is wrong here, but I get this message, when I try to get the Candy Amount

https://gyazo.com/5f46e52b21da40ae88c5aae83c690bf2

Thanks

**Comment by NicklasWallgren** [comment]
That status code indicates that the pokemon go backend servers are overloaded. Wait a bit and try again :)

**Comment by sensityy** [comment]
oh awesome, thanks for quick answer :)
