### ISSUE TITLE
 Call to a member function getOptions() on null 

### ISSUE THREAD

**Issue by xmillies** [NicklasWallgren/PokemonGoAPI-PHP#163]
After the issue **Incorrect wire format for field 3 #160** we are facinf now to another issue : 

`Fatal error: Uncaught Error: Call to a member function getOptions() on null in C:\WTServer\WWW\pogo\vendor\google\protobuf\php\src\Google\Protobuf\descriptor.php:468 Stack trace: #0 C:\WTServer\WWW\pogo\vendor\google\protobuf\php\src\Google\Protobuf\Internal\Message.php(77): Google\Protobuf\Internal\FieldDescriptor->isMap() #1 C:\WTServer\WWW\pogo\vendor\nicklasw\pkm-go-api\src\Requests\GetJournalRequest.php(37): Google\Protobuf\Internal\Message->__construct() #2 C:\WTServer\WWW\pogo\vendor\nicklasw\pkm-go-api\src\Handlers\RequestHandler.php(218): NicklasW\PkmGoApi\Requests\GetJournalRequest->getMessage() #3 C:\WTServer\WWW\pogo\vendor\nicklasw\pkm-go-api\src\Handlers\RequestHandler.php(122): NicklasW\PkmGoApi\Handlers\RequestHandler->build(Object(NicklasW\PkmGoApi\Requests\GetJournalRequest)) #4 C:\WTServer\WWW\pogo\vendor\nicklasw\pkm-go-api\src\Services\Request\JournalRequestService.php(21): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetJournalRequest)) #5 C:\WTServer\WWW\pogo\v in C:\WTServer\WWW\pogo\vendor\google\protobuf\php\src\Google\Protobuf\descriptor.php on line 468`

This was obtained with sample RetrieveJournalExample.php.

Error obtained with the call ** $journal->getPokemons();** in the loop.

**Comment by NicklasWallgren** [comment]
@xmillies Have you updated the dependencies?

 ```composer update```

**Comment by xmillies** [comment]
Yes. I have also tried with removing all vendor(s). You can try with the account I have previously sent to you.

**Comment by NicklasWallgren** [comment]
The problem was due to dependency issues, my bad. Try the latest release v2.0

**Comment by NicklasWallgren** [comment]
@xmillies Can you reproduce the issue in v2.0.1?

**Comment by xmillies** [comment]
Now with v2.0, I get the error on issue #164.
So we can close this case.
