### ISSUE TITLE
Update vendor/nicklasw/pkm-go-api/src/Api/Pokemon/Data/PokemonMetaRegistry.php

### ISSUE THREAD

**Issue by xmillies** [NicklasWallgren/PokemonGoAPI-PHP#165]
The pokemon meta registry needs to be updated with new pokémons :

`Notice: Undefined offset: 174 in C:\WTServer\WWW\pogo\vendor\nicklasw\pkm-go-api\src\Api\Pokemon\Data\PokemonMetaRegistry.php on line 26`

Where do you take previous data ?

**Comment by NicklasWallgren** [comment]
@xmillies The information comes from the GAME_MASTER file https://gist.github.com/elfinlazz/5c7e33be1292329f61f1023a79251cc3

Anyone up for the task?

**Comment by voxx** [comment]
Here yah go.

Two attachments. 
1) A script used to parse the json and output the relevant php.
2) The additional php objects to add to PokemonMetaRegistry.php


[export-meta.php.txt](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/files/679544/export-meta.php.txt)

[PokemonMetaRegistry.php.txt](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/files/679546/PokemonMetaRegistry.php.txt)

**Comment by NicklasWallgren** [comment]
@voxx Nice addition 👍 Could you update the PokeMetaRegistry and make a pull request? :)

**Comment by voxx** [comment]
@NicklasWallgren PR created as requested.

-> https://github.com/NicklasWallgren/PokemonGoAPI-PHP/pull/168

**Comment by NicklasWallgren** [comment]
Resolved by @voxx

**Comment by NicklasWallgren** [comment]
Fixed a minor issue with suffixes. 

https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/2e955389cae3269584282f8283a683f6eb3b5bfe
