### ISSUE TITLE
Where did getType1String() go?

### ISSUE THREAD

**Issue by baskettcase** [NicklasWallgren/PokemonGoAPI-PHP#166]
There used to be a method to get the pokemon type getType1String(), but I can't find it in the Pokemon.php file any longer. There used to be getMove1String() also, but looks like it has changed to getMov1, so that was easy to figure out, but for the life of me I can't figure out the pokemon type... ideas?

**Comment by NicklasWallgren** [comment]
The method is still located in `NicklasW\PkmGoApi\Api\Pokemon\Support` trait which is used in `NicklasW\PkmGoApi\Api\Pokemon` :)

**Comment by baskettcase** [comment]
Thanks, I found that it was renamed to getType1 also, but yeah in a different file. Thanks! :)
