### ISSUE TITLE
Pokémon Go 0.51.2 API using public hashing server

### ISSUE THREAD

**Issue by BlaayLock** [NicklasWallgren/PokemonGoAPI-PHP#169]
it is necessary to apply for an authorization key to this script work?  See https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

Else, why i can not Retrieve the player stats? 

inventory = $pokemonGoApi->getInventory();

NicklasW\PkmGoApi\Api\Player\Inventory Object
(
    [data:protected] => 
)

Use php 7.

**Comment by BlaayLock** [comment]
Oops! Available new doc https://talk.pogodev.org/d/54-getting-started-with-our-api-hashing-service

**Comment by NicklasWallgren** [comment]
@BlaayLoock No it isn't, have a look at the examples in the examples folder.
