### ISSUE TITLE
User Profile Details

### ISSUE THREAD

**Issue by rohit1290** [NicklasWallgren/PokemonGoAPI-PHP#170]
I was looking at the examples, and I want to know one thing. How can I get user profile details like username, team name, level etc.

It will be great if you can direct me to an appropriate document.

**Comment by NicklasWallgren** [comment]
Take a look at the `RetrievePlayerProfileExample` and `RetrievePlayerStatsExample`. 

The library is fairly self-documented, but a documentation would have been nice. Any takers? ;)

**Comment by rohit1290** [comment]
Hi again, I was trying to test the api. I downloaded the source. Executed composer install command. 

Now when I was studying the codes, the first line says require __DIR__ . '/../vendor/autoload.php' but i am not able to find the autoload.php file in the repo.

kindly help.

**Comment by xmillies** [comment]
1° git clone https://github.com/NicklasWallgren/PokemonGoAPI-PHP.git
(or unzip the downloaded zip file)

2° run the command in the root folder of the project (where the file **composer.json** is present) :
composer install

> composer will create the autoload file.

3° copy one sample and adapt it :
correct the line with autoload.php : the folder
put your identity inside.

4° run the script

> if you don't have composer on your computer : [https://getcomposer.org/download/](https://getcomposer.org/download/)

**Comment by rohit1290** [comment]
Thank You! Probably there was an internet problem. Composer install was not creating the vendor folder.

Now everything is in place.
