### ISSUE TITLE
Hashing Server

### ISSUE THREAD

**Issue by baskettcase** [NicklasWallgren/PokemonGoAPI-PHP#173]
Hi Nicklas, can we use our hashing key with this library?

**Comment by NicklasWallgren** [comment]
No sorry, it's not supported in the current version.

**Comment by baskettcase** [comment]
Ok thanks. So this would mean that it's pretty easy to get our account flagged if we use this currently?

**Comment by NicklasWallgren** [comment]
Probably yes, but none of my test accounts has been banned as of yet.

**Comment by NicklasWallgren** [comment]
Can we close this issue?

**Comment by baskettcase** [comment]
Yeah Ill close it. It would still be nice for the future.
