### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by hwiVeloper** [NicklasWallgren/PokemonGoAPI-PHP#174]
I wanna change pokemon's name to my country's language.
How can I convert pokemon's name or movement's name?(e.g. Bulbasaur, hydro pump etc..)

(I also wanna maintain original name source - pogoprotos-php/src/POGOProtos/Enums/*)

**Comment by NicklasWallgren** [comment]
You'll have to do it outside the library, since it doesn't support that type of functionality.

**Comment by xmillies** [comment]
I do like this.
```
class IXLA
{
    // 801 pokémons (source http://www.pokemon.com/fr/pokedex/)
    const POKEMON_FRENCH_NAME = array (
        1 => 'Bulbizarre',
        2 => 'Herbizarre',
        ....
        798 => 'Katagami',
        799 => 'Engloutyran',
        800 => 'Necrozma',
        801 => 'Magearna',
    );
}


Call : 

'nameFr' => IXLA::POKEMON_FRENCH_NAME[$i]


```

**Comment by hwiVeloper** [comment]
@xmillies Thanx! I solved the problem :) 👍
