### ISSUE TITLE
Not work auth with Google and PTC

### ISSUE THREAD

**Issue by efor74** [NicklasWallgren/PokemonGoAPI-PHP#18]
With PTC error:
"
PHP Fatal error:  Uncaught exception 'Exception' with message 'write_varint(): Error writing byte' in PokemonGoAPI-PHP/includes/protocolbuffers.inc.php:642
Stack trace:
#0 PokemonGoAPI-PHP/res/POGOProtos/Networking/Envelopes/RequestEnvelope.php(330): Protobuf::write_varint(Resource id #153, 8145806132888207460)
#1 PokemonGoAPI-PHP/includes/protocolbuffers.inc.php(103): POGOProtos\Networking\Envelopes\RequestEnvelope->write(Resource id #153)
#2 PokemonGoAPI-PHP/src/Handlers/RequestHandler.php(160): ProtobufMessage->toProtobuf()
#3 ... in PokemonGoAPI-PHP/includes/protocolbuffers.inc.php on line 642
"

With Google error:
"
PHP Fatal error:  Cannot use object of type stdClass as array in PokemonGoAPI-PHP/src/Authenticators/GoogleOauth/Parsers/Results/AuthenticationTokenResult.php on line 46
"
![image](https://cloud.githubusercontent.com/assets/20710692/17237464/929c53ac-556b-11e6-834f-f07ad07b1eff.png)

What the problem?

**Comment by NicklasWallgren** [comment]
It would be helpful if you could send the log file to nicklas.wallgren@gmail.com

Thanks.

**Comment by efor74** [comment]
Hello
Log send

Thanks

**Comment by NicklasWallgren** [comment]
Alright, the problem is probably due to PHP running as 32-bit. At this time the protocol buffer parser requires PHP running as 64-bit (or maybe PHP 7).

**Comment by efor74** [comment]
It is bad

**Comment by NicklasWallgren** [comment]
What type of error do you get if you run the latest version?

**Comment by efor74** [comment]
After the upgrade, it worked! Thank you!
