### ISSUE TITLE
Is there a way to get Pokemon by cp?

### ISSUE THREAD

**Issue by DragonStar01** [NicklasWallgren/PokemonGoAPI-PHP#19]
$pokeBank = $inventory->getItems()->getPokeBank();
       // print_r($pokeBank);

        $pokemon = $pokeBank->getPokemonsByType(PokemonId::RATTATA);
        print_r($pokemon);

Prints that i have 2 Rattata 
So i just want to print the Rattatas Cp 
and transfer the lowest one.
How can i do?
Thank you for everything :) 
I was having many errors in this script but when i updated my php version to php7 all the errors gone away 
sorry for my bad English

**Comment by NicklasWallgren** [comment]
This should do it.

      ```
  // Retrieve pokemons of type rattata
  $pokemons = $pokeBank->getPokemonsByType(PokemonId::RATTATA);

  printf('Found %s number of rattats' . PHP_EOL, count($pokemons));

  // Sort the pokemons by combat points
  uasort($pokemons, function (\NicklasW\PkmGoApi\Api\Pokemon\Pokemon $pokemon1, \NicklasW\PkmGoApi\Api\Pokemon\Pokemon $pokemon2) {
            return $pokemon1->getPokemonData()->getCp() <=> $pokemon2->getPokemonData()->getCp();
        });

  // Retrieve the lowest pokemon
  $lowestPokemon = current($pokemons);

  printf('Transfer rattata with cp of %s' . PHP_EOL, $lowestPokemon->getPokemonData()->getCp());

   // Transfer the pokemon
    $lowestPokemon->transfer();

```

**Comment by DragonStar01** [comment]
Thank you very much :) BTW How can i change the response to json?

**Comment by NicklasWallgren** [comment]
What response? The list of pokemon?

**Comment by DragonStar01** [comment]
Sorry my bad
