### ISSUE TITLE
How to get value of Stardust and pokecoins

### ISSUE THREAD

**Issue by DragonStar01** [NicklasWallgren/PokemonGoAPI-PHP#20]
i am new in class php 
The response
```
NicklasW\PkmGoApi\Api\Player\Data\Profile\Currencies Object
(
    [currencies:protected] => Array
        (
            [0] => NicklasW\PkmGoApi\Api\Player\Data\Profile\Currency Object
                (
                    [name:protected] => POKECOIN
                    [amount:protected] => 0
                )

            [1] => NicklasW\PkmGoApi\Api\Player\Data\Profile\Currency Object
                (
                    [name:protected] => STARDUST
                    [amount:protected] => 17100
                )

        )

)
```
I want to print it like this => **You have x stardust and x POKECOIN**
but i cant find a way as i am new to class php 
as in #19 i tried uasort() method but i get a **Warning: uasort() expects parameter 1 to be array** 
whenever i tried to convert it to array it won't convert.
Can you please help me with this ?

```
  $currency = $profileData->getCurrencies();

        uasort($currency, function (\NicklasW\PkmGoApi\Api\Player\Data\Profile\Currencies $c) {
            return $c->getState();
        });
```

**Comment by Ni42** [comment]
You get the array of currencies like this:
```php
$currencies = $profileData->getCurrencies()->getCurrencies();

foreach($currencies as $currency) {
    echo 'Currency '.$currency->getName().': '.$currency->getAmount()."\n";
}
```

I'm not sure if the order is stable, if it is, you could index $currencies just like a normal array.

**Comment by NicklasWallgren** [comment]
// Retrieve the stardust currency
$stardust = $profileData->getCurrencies()->getByType(Currencies::CURRENCY_TYPE_STARDUST);

or 

// Retrieve the list of currencies 
$currencies = $profileData->getCurrencies()->toArray();

// Retrieve the stardust currency
$stardust = $currencies[Currencies::CURRENCY_TYPE_STARDUST];

**Comment by DragonStar01** [comment]
@NicklasWallgren  when i try your method i get this error **Fatal error: Uncaught Error: Class 'Currencies' not found in**
and i get the same error when i try @Ni42  method

**Comment by Ni42** [comment]
Do you have a current version installed? You also need to import the correct classes.
If you have that, post more of your source code, as small as possible to still show the error.

**Comment by DragonStar01** [comment]
Thanks @Ni42  and @NicklasWallgren 
But 
i get this error after i updated to new version 
**WARNING. Invalid log file path provided. The path is not writable. ''**
env file 
```
DEBUG=false
LOG_FILE_PATH= "test.log"
LOG_LEVEL=100
SSL_VERIFICATION=false
```
when i run `echo (true === is_writable('test.log')) ? 'yes' : 'no';` the response is` yes`

**Comment by NicklasWallgren** [comment]
@DragonStar01 Fixed in the latest version. I have changed the way the environment variable file is setup.

**Comment by DragonStar01** [comment]
@NicklasWallgren  Thank you very much :) :+1:
