### ISSUE TITLE
 Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by Spettacolo83** [NicklasWallgren/PokemonGoAPI-PHP#21]
Hello there,
thank you for these fantastic API!
I've put all the files include the vendor directory into my website and modified the example php file "RetrievePlayerProfile.php" with my login.
When I run it, my browser said:

Parse error: syntax error, unexpected '[' in /home/puffo83/public_html/pokeapi/vendor/illuminate/support/helpers.php on line 358

but that line of code is perfect without error!

How can I fix it? Can you suggest me any guide? Thank you very much!

**Comment by DragonStar01** [comment]
Update your php version to 7 it should work fine

**Comment by Spettacolo83** [comment]
Thank you so much! I can't update to php 7 on my website, but I could on my mac, so I've updated and after that the web error now is:

( ! ) Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 35: SSL: CA certificate set, but certificate verification is disabled (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Library/WebServer/Documents/pokemongo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
( ! ) GuzzleHttp\Exception\ConnectException: cURL error 35: SSL: CA certificate set, but certificate verification is disabled (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Library/WebServer/Documents/pokemongo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

Do you know how can I fix it? Thank you again!

**Comment by NicklasWallgren** [comment]
Try changing the SSL_VERIFICATION environment variable to true. 

SSL_VERIFICATION=true

**Comment by Spettacolo83** [comment]
Thank you @NicklasWallgren !
I'm trying to do that but without success!
Can you help me to change that environment variable to true.
Thank you very much!

**Comment by NicklasWallgren** [comment]
Make a copy of the ".env.example file", name it ".env".
Then add the file path as the forth parameter to the ApplicationKernel constructor. 

```
// Initialize the pokemon go application
$application = new ApplicationKernel('INSERT_EMAIL', 'INSERT_PASSWORD', Factory::AUTHENTICATION_TYPE_GOOGLE);
```

**Comment by Spettacolo83** [comment]
I tried in this way:
1) Modifying .env file in this way:
```
DEBUG=false
LOG_FILE_PATH=
LOG_LEVEL=100
SSL_VERIFICATION=true
```

2) Modifying the initialize function in example file RetrievePlayerProfile.php in this way:

```
$application = new ApplicationKernel(
            'xxx-my-username-xxx', 'xxx-my-password-xxx', Factory::AUTHENTICATION_TYPE_GOOGLE, '/Library/WebServer/Documents/pokemongo/.env
');
```


```
( ! ) Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 51: SSL: certificate verification failed (result: 5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Library/WebServer/Documents/pokemongo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
( ! ) GuzzleHttp\Exception\RequestException: cURL error 51: SSL: certificate verification failed (result: 5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Library/WebServer/Documents/pokemongo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187
```

Can I try others things?

**Comment by NicklasWallgren** [comment]
Seems to be a problem related to OSX.

https://github.com/Homebrew/legacy-homebrew/issues/32019

**Comment by Spettacolo83** [comment]
I fixed it installing MAMP with PHP 7!
