### ISSUE TITLE
Suggestion: sort invetory pokemon

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#23]
You could consider the idea to extend the method to obtain the pokemons in your inventory, by adding a parameter "sortby", with # pokedex, name, CP, level and IV (if you can calculate and store the Individual Value of each pokemon)

**Comment by NicklasWallgren** [comment]
Already, the PokeBank now returns a PokemonCollection on which you can sort by name, level, cp, pokedex index and IV ratio.

Have a look.

**Comment by fgala** [comment]
This is working just fine, tested with the Pokemon Collection

**Comment by NicklasWallgren** [comment]
Resolved.

**Comment by paoloalby** [comment]
As in game, I tried to sort PokemonCollection by Pokedex Index.
In game, when I sort by pokedex index or by name, Pokemons with the same name or the same pok# are then sorted automatically by CP (desc).

Here, as we can see in the image attached, we have 3 Weedle with CP unsorted.

Is there a way to make that once we sort by name or pokedex #, it automatically sort by CP desc too?

Like in database queries: "sort by name asc, cp desc"

![order by](https://cloud.githubusercontent.com/assets/15869726/17319122/b6bb515c-588b-11e6-8e0c-a4a2faf2e3f4.png)

**Comment by NicklasWallgren** [comment]
Try the following snippet 

```
$pokemons = $pokemons->sort(function (Pokemon $a, Pokemon $b) {
            if ($a->getPokemonId() != $b->getPokemonId()) {
                return ($a->getPokemonId() < $b->getPokemonId()) ? -1 : 1;
            }
            return $a->getCp() - $b->getCp();
        });
```

**Comment by paoloalby** [comment]
I can't make it works. I'm sure doing something wrong.

First I get the pokemons, sorted by PokedexIndex

`$pokemons = $pokeBank->getPokemons()->sortByPokedexIndex();`
		
Then I write your snippet
		
```
$pokemons = $pokemons->sort(function (Pokemon $a, Pokemon $b) {
            if ($a->getPokemonId() != $b->getPokemonId()) {
                return ($a->getPokemonId() < $b->getPokemonId()) ? -1 : 1;
            }
            return $a->getCp() - $b->getCp();
        });
```
But it gives me errors

> 
Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of Pokemon, instance of NicklasW\PkmGoApi\Api\Pokemon\Pokemon given

**Comment by NicklasWallgren** [comment]
This should sort by pokemon id and CP.

```
$pokebank->getPokemons();

$pokemons = $pokemons->sort(function ($a, $b) {
            if ($a->getPokemonId() != $b->getPokemonId()) {
                return ($a->getPokemonId() < $b->getPokemonId()) ? -1 : 1;
            }
            return $a->getCp() - $b->getCp();
        });
```

**Comment by paoloalby** [comment]
ok, now it works perfectly.

I just changed the return at the end

```
$pokemons = $pokemons->sort(function ($a, $b) {
            if ($a->getPokemonId() != $b->getPokemonId()) {
                return ($a->getPokemonId() < $b->getPokemonId()) ? -1 : 1;
            }
            return $b->getCp() - $a->getCp();
        });
```

So, I get the highest CP first
