### ISSUE TITLE
Suggestion: After Authenticators and use token to get player information

### ISSUE THREAD

**Issue by milowei** [NicklasWallgren/PokemonGoAPI-PHP#25]
For now, every time refresh or use a new function this will send a request to google get authenticator. I think may be just send once request and use token to get information after.

**Comment by Ni42** [comment]
Maybe just add a (configurable) cache for the login tokens or even other data.
Work against the PSR-6 interface and everyone can use his preferred implementation.

**Comment by NicklasWallgren** [comment]
The authentication process is only done once per ApplicationKernel instance, not per request.

We need to handle the token TTL before adding any sort of caching mechanism. But I like the idea.

**Comment by milowei** [comment]
ya, thats true. if you can do that i think it will be nice for communicate
