### ISSUE TITLE
shows [pokemoncaughtbytype] => Rk�)B1 after i use getstats()

### ISSUE THREAD

**Issue by milowei** [NicklasWallgren/PokemonGoAPI-PHP#26]
Im try to get stats and the pokemonCaughtByType is Rk�)B1, 

$pokemonGoApi->getInventory()->getItems()->getStats()->getPokemonCaughtByType();
whats the encode should be?

**Comment by NicklasWallgren** [comment]
It's not possible to decode "pokemon_caught_by_type" as of yet.

**Comment by Spettacolo83** [comment]
Hello there,
how can I get the info about all pokemon into pokemons array?

```
$pokemons = $pokemonGoApi->getInventory()->getItems()->getPokeBank();
for($i=0; $i<sizeof($pokemons); $i++)
{
    echo $pokemons[i]->getPokemonId(); // <- This line does not work
}
```
