### ISSUE TITLE
.

### ISSUE THREAD

**Issue by milowei** [NicklasWallgren/PokemonGoAPI-PHP#28]

**Comment by milowei** [comment]
Is there have a function which can get the pokemon data id = XXX?

like
$Inventory->getItems()->getPokeBank()->getPokemonId( 3064789384737379769 );
not
$Inventory->getItems()->getPokeBank()->getPokemonId( PokemonId::PIDGEY );

**Comment by NicklasWallgren** [comment]
Is this issue still relevant?
