### ISSUE TITLE
getPokemonFabilyId doesn't work every time

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#29]
When I tried to get the $pokemon->getCandies()->getCount() I get few errors with some Pokemon.
Then, I looked deepest in the code and I found out that there's something wrong in the getPokemonFabilyId method.

So, I added few row of code to debug this method and sometimes, it doesn't go recursive. In most of cases yes, but sometimes not.

In the example I attached, in the block 3 it writes "found ID 11" but the family of Caterpie it's 10.
And then I get the error 

Invalid pokemon family id provided. Pokemon family id '11' in C:\wamp64\www\PokemonGoAPI-PHP\src\Api\Player\Data\Inventory\CandyBank.php on line 53

because it's true: pokemon family id 11 doesn't exist in PokemonFamilyId.php

Another weird thing is that it not always echo "Looking for ID: xxx", but only echo "Found Family ID: xxx" and maybe these 2 errors are connected each others.

![candy1](https://cloud.githubusercontent.com/assets/15869726/17319803/9761ac98-5890-11e6-9c2b-467fc3574c18.png)
![candy2](https://cloud.githubusercontent.com/assets/15869726/17319802/9760d1ce-5890-11e6-884c-6a2d83603574.png)

**Comment by paoloalby** [comment]
I found the error.

Just add "return" to the recursive call.

![sol](https://cloud.githubusercontent.com/assets/15869726/17320762/6eb2356a-5895-11e6-9075-d0fd9ea0758d.png)

**Comment by NicklasWallgren** [comment]
Nice catch, create a pull request :)

**Comment by NicklasWallgren** [comment]
Resolved.
