### ISSUE TITLE
For now we only support PHP on 64bit platform

### ISSUE THREAD

**Issue by cinek19** [NicklasWallgren/PokemonGoAPI-PHP#30]
For now we only support PHP on 64bit platform

What should I do?

**Comment by NicklasWallgren** [comment]
Install 64-bit version of PHP.

**Comment by cinek19** [comment]
PHP7?

I tryed with XAMPP or EasyPHP, but does not work.

I'm trying with PHP7 from here http://windows.php.net/download/

**Comment by cinek19** [comment]
I cannot execute it, can you help me?

**Comment by paoloalby** [comment]
install Wamp 64 bit, it includes php 5.6 and php 7.0
With php 7.0 it works perfectly

**Comment by cinek19** [comment]
Already did! It works!
