### ISSUE TITLE
ReleasePokemonResponse syntax error

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#31]
After few days working on my local server, I tried to upload my project on a web server.
Everything works ok, I can read the player data, the inventory, pokebank.
But when I try to "release" a pokemon, I get an error.
On my local web server not. Only on the version I uploaded online.

**Parse error:** syntax error, unexpected 'UNSET' (T_UNSET), expecting identifier (T_STRING) in /mydomain.ext/res/POGOProtos/Networking/Responses/**ReleasePokemonResponse.php** on line **15**

Note that the release action it's ok, if I go back to previous page where I list my pokemon, the Pokemon selected has been released succeffully.

But I still get this error that stops the redirecting action.

**Comment by Ni42** [comment]
Which PHP version do you have on the server? Sounds like the same problem as in #27, class constants need PHP version 5.3.0, but you should really be at 5.6.X anyways.

**Comment by NicklasWallgren** [comment]
Try the latest commit, the keyword "UNSET" is reserved in PHP 5.6.

@Ni42 Thanks for helping out.

**Comment by paoloalby** [comment]
Ok, using NONE instead of UNSET it's working now
