### ISSUE TITLE
Parse error: syntax error, unexpected 'UNSET' (T_UNSET)

### ISSUE THREAD

**Issue by milowei** [NicklasWallgren/PokemonGoAPI-PHP#32]
im trying this code on godaddy server and php vision is 5.6
when i trying transfer pokemon and this happened:

Parse error: syntax error, unexpected 'UNSET' (T_UNSET), expecting identifier (T_STRING) in /API/res/POGOProtos/Networking/Responses/ReleasePokemonResponse.php on line 15

**Comment by NicklasWallgren** [comment]
Try the latest commit, the keyword "UNSET" is reserved in PHP 5.6.

**Comment by paoloalby** [comment]
Ok, using NONE instead of UNSET it's working now

**Comment by NicklasWallgren** [comment]
Resolved.
