### ISSUE TITLE
getPokedexItems is empty

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#33]
$pokedex = $inventory->getItems()->getPokedex()->getPokedexItems()

This shoud give me all pokedex info about my pokemon in pokedex (pokedexEntryNumber, timesEncountered, timesCaptured , etc)

But if I print the $pokedex array:

Array ( [0] => NicklasW\PkmGoApi\Api\Player\Data\Inventory\PokedexItem Object ( [pokedexEntryNumber:protected] => 0 [timesEncountered:protected] => 2 [timesCaptured:protected] => 2 [evolutionStonePieces:protected] => 0 [evolutionStones:protected] => 0 ) ) 

it's empty, no data stored.

**Comment by NicklasWallgren** [comment]
Resolved.
