### ISSUE TITLE
For the beginner

### ISSUE THREAD

**Issue by Bigg-Mike** [NicklasWallgren/PokemonGoAPI-PHP#36]
Hi,

i have this message when i try to run a example class:

"php RetrievePlayerStatsExample.php
For now we only support PHP on 64bit platforms \n"

I work on Windows 10 - 64bit.

Thanks for the API, from France!

**Comment by Ni42** [comment]
Do you have a 64bit PHP version installed? What does `echo PHP_INT_SIZE; ` give you?

**Comment by Bigg-Mike** [comment]
Ok I find the exception in the code but i'm a beginner...

"if (PHP_INT_SIZE !== 8) {
	echo 'For now we only support PHP on 64bit platforms \n';

    die();
}"

It give me: 4

I work with Laravel and PHP 7.0.0RC2

**Comment by Ni42** [comment]
Yeah, that looks like 32bit. If you want to be sure about the PHP version, see what `phpinfo()` says about the architecture. You'll have to install a 64bit PHP version if it says x86. There are some guides on the Laragon forum, maybe check there first.

**Comment by paoloalby** [comment]
download WAMP64 and install it.
select then php 7 and not php 5.6 and you will have php 64 bit

**Comment by Bigg-Mike** [comment]
I install 64 bits PHP version (x64) with laragon but still the same problem.

Thanks @paoloalby it's work with WAMP :)

**Comment by jibarra-xx** [comment]
The code that displays this error is found in the following files:
src\protocolbufferes.inc.php
includes\protocolbuffers.inc.php

You can try commenting it out, but not sure if it's recommended or what implications it will have.
 /*
if (PHP_INT_SIZE !== 8) {
	echo 'For now we only support PHP on 64bit platforms \n';

    die();
}
*/
