### ISSUE TITLE
get current Trainer exp level

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#37]
Hi, I'm trying to rigure out how to get the current exp level.

We have only these 3 methods:

```
$Experience = $playerStats->getExperience();
$PrevLevelXp = $playerStats->getPrevLevelXp();
$getNextLevelXp = $playerStats->getNextLevelXp();
```

In my case, I'm level 28 and I get these values (check the red rectangle)

![immagine](https://cloud.githubusercontent.com/assets/15869726/17396824/6b5729e2-5a35-11e6-81b7-e5faf6f9de0b.png)

In game I can see this other 2 info:

Current Exp: 3665		
Exp for THIS level: 300000

With 

`$getNextLevelXp - $Experience`

I get te Exp needed to next level, same if I do 300000-3665

Same result: 296335

I'd like to write, like in game 296335/300000, but this "300000" value is not calculated in method in this API, or yes?
There's any way to get this value?

**Comment by NicklasWallgren** [comment]
The required exp can be found in the GAME_MASTER.protobuf file and is not returned from the server.
It would have been nice with a sqlite database where we could store game specific information.

```
 TemplateId: "PLAYER_LEVEL_SETTINGS"
  PlayerLevel {
    RankNum: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    RequiredExp: [0, 1000, 3000, 6000, 10000, 15000, 21000, 28000, 36000, 45000, 55000, 65000, 75000, 85000, 100000, 120000, 140000, 160000, 185000, 210000, 260000, 335000, 435000, 560000, 710000, 900000, 1100000, 1350000, 1650000, 2000000, 2500000, 3000000, 3750000, 4750000, 6000000, 7500000, 9500000, 12000000, 15000000, 20000000]
    CpMultiplier: [0.094, 0.166398, 0.215732, 0.25572, 0.29025, 0.321088, 0.349213, 0.375236, 0.399567, 0.4225, 0.443108, 0.462798, 0.481685, 0.499858, 0.517394, 0.534354, 0.550793, 0.566755, 0.582279, 0.5974, 0.612157, 0.626567, 0.640653, 0.654436, 0.667934, 0.681165, 0.694144, 0.706884, 0.719399, 0.7317, 0.737769, 0.743789, 0.749761, 0.755686, 0.761564, 0.767397, 0.773187, 0.778933, 0.784637, 0.7903]
    MaxEggPlayerLevel: 20
    MaxEncounterPlayerLevel: 30
  }
```

**Comment by Ni42** [comment]
Maybe just make a small PHP file, seeing as the information is pretty static, so you don't have the overhead of DB queries. I might even do a pull request once I figure that out ... :)

**Comment by NicklasWallgren** [comment]
I made a quick and dirty port of https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/pokemon/PokemonMetaRegistry.java

I will have to do for now

**Comment by Ni42** [comment]
But that looks fine for now? ;)

**Comment by NicklasWallgren** [comment]
It will suffice for now #hides

**Comment by Ni42** [comment]
Well, it doesn't solve the XP thingy, so might still try and do that ;)

**Comment by NicklasWallgren** [comment]
Resolved by Ni42.
