### ISSUE TITLE
Evolving check 

### ISSUE THREAD

**Issue by Gnacik** [NicklasWallgren/PokemonGoAPI-PHP#38]
Is there a method showing if pokemon can be evolved ? 
Cannot find it :(

Im making simple web to show whole inventory and pokemons, i want to display candies for pokemons that can be evolved.

**Comment by NicklasWallgren** [comment]
No sorry, the API does not contain game-specific meta information about pokemon. Hopefully someone has time to add that.

You can find the needed data here.
https://gist.github.com/nneonneo/ba1382b26e61c926a3e385ca6fed0e51

**Comment by NicklasWallgren** [comment]
I'll add it tomorrow.

**Comment by NicklasWallgren** [comment]
`$pokemon->canEvolve()`

**Comment by Gnacik** [comment]
Thanks! :+1:
