### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by RikudouSage** [NicklasWallgren/PokemonGoAPI-PHP#4]
In `PokemonGoAPI-PHP/res/POGOProtos/Networking/Requests/RequestType.php` on line 76 there is  `const ECHO = 666;`.

On php `5.6.24-1` it creates parse error, because echo is reserved keyword.

**Comment by NicklasWallgren** [comment]
My bad, the problem does not affect PHP 7.0

Fixed in latest commit.

**Comment by baskettcase** [comment]
This needs to be fixed again...

**Comment by NicklasWallgren** [comment]
@baskettcase I have filled an issue on this particular error here; https://github.com/google/protobuf/issues/2546

**Comment by NicklasWallgren** [comment]
@baskettcase Manually patched in https://github.com/NicklasWallgren/pogoprotos-php/commit/8a8e699290a041d3e8c681a2476c7b6bbde98e56
