### ISSUE TITLE
Request: Check if Lucky Egg is set

### ISSUE THREAD

**Issue by lambasoft** [NicklasWallgren/PokemonGoAPI-PHP#40]
Hey,
It would be great if you could add the option to check either a Lucky egg is set or not.

**Comment by Ni42** [comment]
Pretty sure the server doesn't tell you from the API whether lucky egg is active or not.

**Comment by NicklasWallgren** [comment]
I believe you can find the information within AppliedItems.

```
// Retrieve the applied items instance
$appliedItems = $inventory->getAppliedItems();

// Retrieve the items within the applied items instance
$items = $appliedItems->getAppliedItems();

var_dump($items);



```

**Comment by Ni42** [comment]
Oh right... So many files all over the place. XD
