### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by sensityy** [NicklasWallgren/PokemonGoAPI-PHP#41]
Hello, when I try to run examples it happens, it's a LAMP Installation from Digitalocean.

It's running 64-Bit as you can see here http://82.196.5.58/PokemonGoAPI-PHP/

http://82.196.5.58/PokemonGoAPI-PHP/examples/RetrievePlayerStatsExample.php Just gives 500 error.

Any ideas?

Thanks in advance.

**Comment by Ni42** [comment]
You might want to check the PHP error log of your server what the problem is.

**Comment by sensityy** [comment]
I'm getting this error

`[Fri Aug 05 10:18:08.073432 2016] [:error] [pid 1420] [CLIENT] PHP Fatal error:  require(): Failed opening required '/var/www/html/PokemonGoAPI-PHP/examples/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/PokemonGoAPI-PHP/examples/RetrievePlayerStatsExample.php on line 3` I have installed with composer

**Comment by Ni42** [comment]
You do have the file /var/www/html/PokemonGoAPI-PHP/examples/vendor/autoload.php (and the web server process can access it?

**Comment by sensityy** [comment]
I only have example files in the folder, this is the root structure. 

https://gyazo.com/c9d0ed977a241570c72410508822e883

**Comment by Ni42** [comment]
So, what's in the vendor folder?

**Comment by sensityy** [comment]
https://gyazo.com/3531ffc680613c4654c1cca13ce82ae4 these 

and this is the autoload.php file 

`<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit413b91017c9ef58e1d182eb2c060fa08::getLoader();
`

**Comment by Ni42** [comment]
Still looks like a permission problem to me. Normally you should get additional PHP warnings before the fatal error about the reason for the fatal error. Might be helpful to temporarily turn on `display_errors` to see all the output.

**Comment by sensityy** [comment]
Apparently it invisible space in my  $application = new ApplicationKernel - it works, sorta now. Now im getting `Parse error: syntax error, unexpected 'ECHO' (T_ECHO), expecting identifier (T_STRING) in /var/www/html/PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Networking/Requests/RequestType.php on line 76`

**Comment by NicklasWallgren** [comment]
@sensityy Update the dependencies

composer update

**Comment by Ni42** [comment]
Damn, too slow, exactly that.

**Comment by sensityy** [comment]
Many many thanks! You guys rock! :-) :+1:

**Comment by NicklasWallgren** [comment]
@Ni42 Better luck next time ;) #toslow
