### ISSUE TITLE
pokemonMeta

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#44]
I saw that in this latest release there are useful information about Pokemons in PokemonMeta.php and PokemonMetaRegistry.php files.

My question now is: how to call these infos once we have our Pokemons get from PokeBank?
I'd need to read the $pokemonMeta->getCandyToEvolve();

**Comment by NicklasWallgren** [comment]
Take a look at the latest commit.

```
$pokemon->canEvolve();
$pokemon->getCandiesToEvolve();
```

**Comment by paoloalby** [comment]
ok! It works like a charm!
