### ISSUE TITLE
RequestType.php ECHO_REQUEST changed

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#46]
In "vendor/nicklasw/pogoprotos-php/src/POGOProtos/Networking/Requests/" folder there is a file "RequestType.php"

In the list of all its const, there is a declaration: "const ECHO = 666;" that give me error at runtime.
I checked the previous version and this declaration was "const ECHO_REQUEST = 666;"

So, now, I put it back to ECHO_REQUEST and I don't have the error anymore. But I'm not sure everything will properly work.

**Comment by NicklasWallgren** [comment]
Update the dependencies.

composer update
