### ISSUE TITLE
pokemonfamilyid

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#49]
the pokemonfamiliy id is missing. so we can't get candy using that value now

**Comment by f2008305** [comment]
ah. also "name:protected" is disappeared...
so no name and no pokemonfamilyid
any chance to having them readded?
in the $pokeBank->getpokemons();

**Comment by Ni42** [comment]
`Pokemon->getName()` and `Pokemon->getFamilyId()` are still there, what doesn't work for you?

**Comment by f2008305** [comment]
ok fixed. i was using different method
