### ISSUE TITLE
Warning: require(C:\xampp\htdocs\poke\examples/../vendor/autoload.php): failed to open

### ISSUE THREAD

**Issue by ps7is** [NicklasWallgren/PokemonGoAPI-PHP#5]
Hello i am getting these errors 
> Warning: require(C:\xampp\htdocs\poke\examples/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\poke\examples\RetrievePlayerStatsExample.php on line 3

and 

> Fatal error: require(): Failed opening required 'C:\xampp\htdocs\poke\examples/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\poke\examples\RetrievePlayerStatsExample.php on line 3

My Current PHP version:

>  5.6.14

thanks

**Comment by NicklasWallgren** [comment]
Have you installed the dependencies? (composer install)

**Comment by ps7is** [comment]
oh! My bad i forgot that.
Thanks For your Help :+1:

**Comment by NicklasWallgren** [comment]
No problem :) I'm closing this issue

**Comment by Dilshan97** [comment]
composer install
 its work for me. thank you

**Comment by abdul-ma** [comment]
HP Warning:  require(C:\xampp\htdocs\my-project/vendor/autoload.php) I am having this problem
