### ISSUE TITLE
attacks and damages

### ISSUE THREAD

**Issue by f2008305** [NicklasWallgren/PokemonGoAPI-PHP#51]
are in the code the attacks and damages of a pokemon?
or can we have only the id of that attack?

**Comment by Ni42** [comment]
You can do `$pokemon->getMove1()` and `$pokemon->getMove2()` to get an integer with the move IDs, but the remaining details you need yourself, this probably also needs some meta files to support the move information.

**Comment by DrDelay** [comment]
You can get the "code-name" by ID with [this](https://github.com/NicklasWallgren/pogoprotos-php/blob/bfb3fce41ff37e8a39e115a20de2c838f3f70d38/src/POGOProtos/Enums/PokemonMove.php#L383). Damage will get tricky though.

**Comment by Gandaflux** [comment]
#63
