### ISSUE TITLE
Help: How to get the OAuth token from this token

### ISSUE THREAD

**Issue by lambasoft** [NicklasWallgren/PokemonGoAPI-PHP#52]
Hey,

PokeAdvisor uses this url to get a token: 
[https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email](url)

How can I use this token to obtain the OAuth token ? Can PokemonGoAPI-PHP be tweaked in a way so it uses the token obtained from the above url ?

**Comment by NicklasWallgren** [comment]
Check out the new authentication system. It will be released later today.

https://github.com/NicklasWallgren/PokemonGoAPI-PHP/tree/authentication-managers

**Comment by NicklasWallgren** [comment]
Resolved
