### ISSUE TITLE
Error - Unexpected end of stream

### ISSUE THREAD

**Issue by jmcquillan** [NicklasWallgren/PokemonGoAPI-PHP#56]
With a fresh install, I tried to up RetrievePokemonCountExample.php (after updating the auth info) and get the error below:

PHP Fatal error:  Uncaught exception 'Exception' with message 'read_bytes(): Unexpected end of stream' in vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php:364

This happens with many of the other example scripts as well.

**Comment by NicklasWallgren** [comment]
@DrDelay It's due the StreamWrapper. hmm, do you have any thought about it?

**Comment by DrDelay** [comment]
I can't reproduce it at f70c9ce943283a8351bccce542cd9bc278f15033 . I tried PlayerProfile and PokemonCount example, both worked.

**Comment by jmcquillan** [comment]
I'm using PTC auth, if that matters... Other than that, it's an unmodified fresh code (git clone, composer install)

**Comment by NicklasWallgren** [comment]
Weird, I could reproduce the problem. Reverted the pull request until we find out what's causing the problem. 

@jmcquillan Try the latest commit.

**Comment by jmcquillan** [comment]
e8d58cc works for me!

**Comment by DrDelay** [comment]
What is your guys environment?
I got PHP 7.0.9 NTS

**Comment by NicklasWallgren** [comment]
Tried both PHP 7.0.3-13 ( NTS ) and PHP 7.0.9-1 ( NTS ). Same issue.

What OS are you using?

**Comment by DrDelay** [comment]
Windows 7, but I just tried it on a Debian Jessie with a `PHP 7.0.9-1~dotdeb+8.1 (cli) ( NTS )` setup, worked aswell :laughing:

**Comment by NicklasWallgren** [comment]
I'm running Ubuntu 14.04. I love these sort of problems... :D

**Comment by DrDelay** [comment]
The condition for the Exception is `if (strlen($bytes) !== $len)`, where `$bytes = fread($fp, $len)`, this text seems a bit misleading. I'm only thinking out loud, can this be character encoding related or something? Like, regional setting of the machine?

**Comment by NicklasWallgren** [comment]
I was thinking the same, it's probably related to encoding. It usually is.

**Comment by DrDelay** [comment]
* mb_string is not relevant (tried dis-/enable)
* Windows is German, `en_US:en` on Debian
* `curl 7.49.1` on Windows, `curl 7.38.0` on Debian

**Comment by jmcquillan** [comment]
en_US PHP 5.6.24 on Mac OS 10.11.6 with curl 7.43.0

**Comment by NicklasWallgren** [comment]
The length of the string returned from stream_get_contents differs between the different streams.

94 (ProtobufIO::toStream)
139-141 (Streamwrapper::getResource)

**Comment by DrDelay** [comment]
Regarding the *mbstring* that like I hastily said doesn't matter, I found a [comment](http://stackoverflow.com/a/6158102) that says one should use `mb_strlen($data, '8bit')` to get the amount of bytes read. I cannot test whether that would fix it, but I can say that it still works with this in my environment. Can someone of you try it out?

**Comment by DrDelay** [comment]
If so and this means we'd have to force every user to use *mbstring*-ext, it may be reasonable to just pass it as a string as this works. I'd still like to figure out the reason of this error.

**Comment by NicklasWallgren** [comment]
Nice find, `mb_strlen($data, '8bit')` did unfortunately no difference.

**Comment by DrDelay** [comment]
I'm kinda out of ideas then.

I added this code to your *unmarshall*-method:
``` php
        // Unmarshall the response

        echo mb_internal_encoding(), PHP_EOL;
        echo mb_http_output(), PHP_EOL;
        echo mb_http_input(), PHP_EOL;
        echo mb_regex_encoding(), PHP_EOL;
        $body = $response->getBody();
        echo 'strlen(body->getContents): ', strlen($body->getContents()), PHP_EOL;
        $body->seek(0);
        echo 'body->getSize: ', $body->getSize(), PHP_EOL;
        $body->seek(0);
        $wrap = \GuzzleHttp\Psr7\StreamWrapper::getResource($body);
        echo 'strlen(streamwrapped): ', strlen(stream_get_contents($wrap)), PHP_EOL;
        $body->seek(0);
        echo 'strlen(toStream): ', strlen(stream_get_contents(\ProtobufIO::toStream($response->getBody()->getContents()))), PHP_EOL;
        die();
```
That results in:
```
UTF-8
UTF-8

UTF-8
strlen(body->getContents): 141
body->getSize: 141
strlen(streamwrapped): 141
strlen(toStream): 141
```
I'm assuming you get different sizes. Maybe you could run that and see what encodings you get.

**Comment by NicklasWallgren** [comment]
Hmm, the problem disappeared after re-installing the dependencies. It could be a bug connected to Guzzle.

Sorry for the late replay, been kind busy today.

**Comment by finalpk** [comment]
I got the same error with one of my accounts, however it works with my other account

**Comment by NicklasWallgren** [comment]
@finalpk Can you reproduce the problem in the latest version?
