### ISSUE TITLE
Get the type of pokemon

### ISSUE THREAD

**Issue by Raphaelbm** [NicklasWallgren/PokemonGoAPI-PHP#59]
Hello again !

I didn't found how can I get the type of pokemon, like water, poison, fire etc...

I tried getPokemonFamilyId but it is return the pokemon id.

If someone can help me ! 

PS: I really like this API ! Thank you very much !

**Comment by Gandaflux** [comment]
```
PokemonType::toString(PokemonMetaRegistry::getByPokemonId($i)->getType1());
```

**Comment by NicklasWallgren** [comment]
How about adding it as a method in PokemonDetailsTrait?

Make a pull request :)

**Comment by Gandaflux** [comment]
#63

**Comment by NicklasWallgren** [comment]
Resolved.
