### ISSUE TITLE
Fatal error: Uncaught exception 

### ISSUE THREAD

**Issue by ps7is** [NicklasWallgren/PokemonGoAPI-PHP#6]
I am having some issues 

> Fatal error: Uncaught exception 'Dotenv\Exception\InvalidPathException' with message 'Unable to read the environment file at C:\xampp\htdocs\poke\src\Kernels/../..\.env.' in C:\xampp\htdocs\poke\vendor\vlucas\phpdotenv\src\Loader.php:75 Stack trace: #0 C:\xampp\htdocs\poke\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\poke\vendor\vlucas\phpdotenv\src\Dotenv.php(90): Dotenv\Loader->load() #2 C:\xampp\htdocs\poke\vendor\vlucas\phpdotenv\src\Dotenv.php(48): Dotenv\Dotenv->loadData() #3 C:\xampp\htdocs\poke\src\Kernels\Kernel.php(105): Dotenv\Dotenv->load() #4 C:\xampp\htdocs\poke\src\Kernels\Kernel.php(84): NicklasW\PkmGoApi\Kernels\Kernel->loadEnvironmentVariables() #5 C:\xampp\htdocs\poke\src\Kernels\ApplicationKernel.php(60): NicklasW\PkmGoApi\Kernels\Kernel->initialize() #6 C:\xampp\htdocs\poke\src\Kernels\Kernel.php(40): NicklasW\PkmGoApi\Kernels\ApplicationKernel->initialize() #7 C:\xampp\htdocs\poke\src\Kernels\ApplicationKernel.php(46): NicklasW\PkmGoApi\Kernels\ in C:\xampp\htdocs\poke\vendor\vlucas\phpdotenv\src\Loader.php on line 75

Please Help me !

**Comment by NicklasWallgren** [comment]
Have you created the environment file?

1. Rename the ".env.example" to  ".env"
2. Set the LOG_FILE_PATH (the full path to the file)
