### ISSUE TITLE
how to install api to xampp, composer

### ISSUE THREAD

**Issue by mahiepit** [NicklasWallgren/PokemonGoAPI-PHP#61]
Sorry, I'm a new member, i downloaded API to my computer and setup composer. But when i go to http://localhost/pokemon/examples/RetrievePlayerProfile.php

Warning: require(D:\xampp\htdocs\pokemon\examples/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\pokemon\examples\RetrievePlayerProfile.php on line 3

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\pokemon\examples/../vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\pokemon\examples\RetrievePlayerProfile.php on line 3

Please help me.. thank you.

**Comment by DrDelay** [comment]
Go to `D:\xampp\htdocs\pokemon\`, open a shell, type `composer install` (the Windows installer should have put it in your path).

**Comment by mahiepit** [comment]
Thank you very much. I did it. Thank you  Thank you Thank you Thank you Thank you Thank you

**Comment by DrDelay** [comment]
That assertion is there for a reason. In another project ( jaspervdm/pogoprotos-php ) we tried another Protobuf lib ( protobuf-php/protobuf-plugin ), that doesn't have that check, but at least for me a bunch of other errors occurs if I try to run it with a 32bit PHP :cry:

**Comment by mahiepit** [comment]
OK,, tks, I will try again with PHP 64bit.

**Comment by mahiepit** [comment]
I setup window 64bit and wamp 64bit but when i run localhost,
http://localhost/pokemon/examples/RetrievePlayerProfile.php
For now we only support PHP on 64bit platforms \n
Help me....

**Comment by DrDelay** [comment]
Consider this an reply also to #64

What do you get if you run `php -r "echo PHP_INT_SIZE;"`? It has to return 8, otherwise it's not a 64bit PHP version. I'd suggest using a PHP installation directly provided from [windows.php.net](http://windows.php.net/), I have one of them working on my Windows machine (not using WAMP/XAMPP, though).
