### ISSUE TITLE
Unexpected end of stream

### ISSUE THREAD

**Issue by GianiWVL** [NicklasWallgren/PokemonGoAPI-PHP#67]
Code I wrote:

        $application = new ApplicationKernel('******@gmail.com', ******', Factory::AUTHENTICATION_TYPE_GOOGLE);
        $pokemonGoApi = $application->getPokemonGoApi();
        $inventory = $pokemonGoApi->getInventory();
        $pokebank = $inventory->getPokeBank(); //line that throws the error

Exception I'm getting is:

    Exception in protocolbuffers.inc.php line 364:
    read_bytes(): Unexpected end of stream

**Comment by DrDelay** [comment]
See #56, this is a weird error. Are you on a revision between 79ebf348abc662451b1a15edb59fe5c448061a46 (incl) and e8d58ccfd4fd90b011a6c8b092166578a55d181c (excl)?

Introduced in #45, using the [StreamWrapper](https://github.com/guzzle/psr7/blob/master/src/StreamWrapper.php) works on some machines, doesn't on others.

**Comment by GianiWVL** [comment]
I'm on revision 12efec3 which is the one just after 79ebf34

**Comment by NicklasWallgren** [comment]
@GianiWVL What happens if you reinstall / update the dependencies?

**Comment by DrDelay** [comment]
The scope I mentioned is where the error occurs. You can either try to find out why it works on some and doesn't on some other installations, or update to after the revert in #57.

**Comment by NicklasWallgren** [comment]
I'll close this issue. Lets continue the discussion in the other issue https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/56
