### ISSUE TITLE
Get journal?

### ISSUE THREAD

**Issue by R3dRidl3** [NicklasWallgren/PokemonGoAPI-PHP#68]
Hello, I love this API, but is there some way I can get the journal of a person?

**Comment by NicklasWallgren** [comment]
Not of yet, will be added eventually :)

**Comment by Ni42** [comment]
FYI I'm working on adding this as a pull request, but it seems like there is a problem with the Proto files right now for that, so that needs to get fixed first before it works flawlessly.

**Comment by R3dRidl3** [comment]
Ok, super that's COOL :)

**Comment by NicklasWallgren** [comment]
The current definition is not entirely correct, but I have managed to unmarshall the response :) 

 ```
 class POGOProtos\Data\Logs\ActionLogEntry#78 (6) {
    private $_unknown =>
    NULL
    private $action =>
    class POGOProtos\Data\Logs\CatchPokemonLogEntry#79 (7) {
      private $_unknown =>
      NULL
      private $result =>
      int(1)
      private $pokemonId =>
      int(133)
      private $combatPoints =>
      int(14)
      private $pokemonDataId =>
      int(0)
      private $_unknown =>
      NULL
      public $playerLatitude =>
      double(1.5432289347407E-229)
    }
```

**Comment by Ni42** [comment]
I got it "working" by removing the wire_type check in the Proto file, but that probably scrambled the data behind the PokemonDataId. I used the protoc --decode_raw and it would only list the 4 fields that were already in the Proto file, too.

**Comment by NicklasWallgren** [comment]
```
// Retrieve the pokemon go api instance
$pokemonGoApi = $application->getPokemonGoApi();

// Retrieve the journal procedure
$journal = $pokemonGoApi->getJournal();

// Retrieve the log entries
$journal->getPokemons();
$journal->getForts();

```

**Comment by Ni42** [comment]
You ... ^^ 
Doesn't work because of the wire_type thingy for now, but nice that the API is just like in my local branch :P

**Comment by NicklasWallgren** [comment]
@Ni42 Have you updated the dependencies? ;) Works fine

**Comment by Ni42** [comment]
Obviously I didn't :[

**Comment by NicklasWallgren** [comment]
Resolved. Thanks @Ni42.

I'll update the definition file at https://github.com/AeonLucid/POGOProtos
