### ISSUE TITLE
'Invalid authentication token provided'

### ISSUE THREAD

**Issue by DragonStar01** [NicklasWallgren/PokemonGoAPI-PHP#7]
Hello , 
Can you tell me how to fix this error 
I am using PTC login 
When i tried to echo token it shows the correct token 
> Fatal error: Uncaught exception 'NicklasW\PkmGoApi\Handlers\RequestHandler\Exceptions\AuthenticationException' with message 'Invalid authentication token provided' in C:\xampp\htdocs\poke\src\Handlers\RequestHandler.php:85 Stack trace: #0 C:\xampp\htdocs\poke\src\Handlers\RequestHandler.php(93): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetInventoryRequest)) #1 C:\xampp\htdocs\poke\src\Services\Request\InventoryRequestService.php(19): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetInventoryRequest)) #2 C:\xampp\htdocs\poke\src\Api\Player\Inventory.php(37): NicklasW\PkmGoApi\Services\Request\InventoryRequestService->getInventory() #3 C:\xampp\htdocs\poke\src\Api\Player\Inventory.php(25): NicklasW\PkmGoApi\Api\Player\Inventory->update() #4 C:\xampp\htdocs\poke\examples\RetrievePlayerStatsExample.php(26): NicklasW\PkmGoApi\Api\Player\Inventory->getItems() #5 C:\xampp\htdocs\PokemonGoPhp\examples\RetrievePlayerStatsExample.php(34): RetrievePlayerStatsEx in C:\xampp\htdocs\PokemonGoPhp\src\Handlers\RequestHandler.php on line 85

When i print token 

> POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo Object ( [_unknown:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo:private] => [provider:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo:private] => ptc [token:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo:private] => POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo_JWT Object ( [_unknown:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo_JWT:private] => [contents:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo_JWT:private] => **TGT-8200905-GIpxnOlc3dmGbcqBhHgratMaYbMMiDQqUG2cPXV71hc3eCYwtx-sso.pokemon.com** [unknown2:POGOProtos\Networking\Envelopes\RequestEnvelope_AuthInfo_JWT:private] => 0 [_unknown:ProtobufMessage:private] => ) [_unknown:ProtobufMessage:private] => )

**Comment by NicklasWallgren** [comment]
Interesting, I can't replicate the problem. 

It could be due to the unstable backend Pokemon GO servers. I will continue the investigation.

**Comment by NicklasWallgren** [comment]
I have improved the error handling in the latest commit. Could you try again? :)

**Comment by DragonStar01** [comment]
Thanks but it still have same error :(

**Comment by tomHash** [comment]
I just had this issue for ages on a brand new PTC account. I'd actually never logged in on the phone before, and when I attempted to I got the same error on my phone. After another try it worked but I still had to accept the license agreement and choose my character, so I'm not sure if it was just a server issue or it was because I hadn't logged in yet, but the error has gone now

**Comment by NicklasWallgren** [comment]
Thanks for the input. It's probably due to the account being in an illegal state. I'm closing this issue.
