### ISSUE TITLE
Use item, delete item

### ISSUE THREAD

**Issue by Gandaflux** [NicklasWallgren/PokemonGoAPI-PHP#70]
Is there possible to use item (egg) and delete items (balls) from inventory using api ?

**Comment by NicklasWallgren** [comment]
Not yet, I'm currently re-working the authentication-system.

**Comment by lambasoft** [comment]
Any updates on the authentication-system @NicklasWallgren ? Pretty much excited over here ^.^

**Comment by Gandaflux** [comment]
@NicklasWallgren  pokemon upgrade will be available too ?

**Comment by Gandaflux** [comment]
#78
