### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by sw45859** [NicklasWallgren/PokemonGoAPI-PHP#72]
I'm not sure if i'm doing something wrong, but when i try to use the google login i get an error that gives a url. when i redirect to that url it just sits there. 

i haven't changed anything in the code so i'm not sure if i should change the oauth setting or set up something on my google account.

can you let me know if there's more to do with the current repo in order to use google login?

**Comment by NicklasWallgren** [comment]
We don't support 2-factor login at this point. You'll be apply to login with refresh token, authentication code, oauth code and user credentials in a upcoming release.
