### ISSUE TITLE
Reserved keyword causing syntax error

### ISSUE THREAD

**Issue by samyex6** [NicklasWallgren/PokemonGoAPI-PHP#73]
In `vendor/nicklasw/pogoprotos-php/src/POGOProtos/Networking/Request/RequestType.php` line 76, since reserved keywords cannot be used as a constant name prior to PHP7, so it will cause a syntax error.

**Comment by NicklasWallgren** [comment]
Sorry, missed that one when i updated the proto files. It's should be sorted now.
