### ISSUE TITLE
Nearby Pokemon

### ISSUE THREAD

**Issue by Es0teric** [NicklasWallgren/PokemonGoAPI-PHP#74]
Hi,

I have been looking through the source code and I see that you have a nearby pokemon feature... If i get the latitude and longitude of the user, is it possible for me to retrieve all nearby pokemon? If so, how would i instantiate the class? if its not possible (because its not in the codebase yet), what would be the api endpoint to get the nearby pokemon?

**Comment by Ni42** [comment]
See #65, until that is resolved, you can't get map resources, because the game API was updated.
