### ISSUE TITLE
After update Fatal error Class 'NicklasW\PkmGoApi\Authenticators\Factory' not found

### ISSUE THREAD

**Issue by efor74** [NicklasWallgren/PokemonGoAPI-PHP#75]
Fatal error: Class 'NicklasW\PkmGoApi\Authenticators\Factory' not found in RetrievePlayerProfile.php on line 18

autoloader not work?

**Comment by DrDelay** [comment]
You can always try `composer dump-autoload`, maybe something's gone wrong creating the autoload files, but I cannot really imagine it.

**Comment by lambasoft** [comment]
I think he missed the whole `composer install`.
@efor74 are you sure you installed required dependencies ?

**Comment by efor74** [comment]
composer install
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Writing lock file
> Generating autoload files

All dependencies are installed. But the error is the same.

**Comment by efor74** [comment]
`var_dump(require( __DIR__ . '/../vendor/autoload.php'))`

http://prntscr.com/c3cwfy

**Comment by DrDelay** [comment]
Looks good..
Does the class exist following the defined PSR-4 structure? `NicklasW\PkmGoApi\Authenticators\Factory => ./src/Authenticators/Factory.php`. Maybe also a permission problem? Directories above should have `r+x`, the file itself atleast `r`.
Did you do any changes (delete it)? `git status`

**Comment by efor74** [comment]
Thank you all!

**Comment by DrDelay** [comment]
Can you tell us what was wrong? I'm kinda curious :laughing:

**Comment by efor74** [comment]
The problem has been in the files
There was no ./src/Authenticators/Factory.php
I deleted everything and reinstalled

**Comment by jibarra-xx** [comment]
Is it only me? 

This is after a new clean install:
I am not seeing ./src/Authenticators/Factory.php. 
I am seeing ./src/Authentication/Factory.php

**Comment by PureDizzi** [comment]
It's my first time using composer. I get fatal error class Config(). I can fix it by using "use" to get all the classes. But, something is definitely wrong here. What do?
