### ISSUE TITLE
Proxy Support? 

### ISSUE THREAD

**Issue by d3vilsn0w** [NicklasWallgren/PokemonGoAPI-PHP#76]
Is it possible for you to add proxy support? As Digital Ocean IP range is banned.

**Comment by kronthto** [comment]
Guzzle has the option to [use a proxy](http://docs.guzzlephp.org/en/latest/request-options.html#proxy), so that shouldn't be too hard. I might do a quick PR for this after work :smile:

**Comment by DrDelay** [comment]
See #83

**Comment by NicklasWallgren** [comment]
Resolved, thanks @DrDelay
