### ISSUE TITLE
How can I set a pokemon as favorite?

### ISSUE THREAD

**Issue by fgala** [NicklasWallgren/PokemonGoAPI-PHP#77]
Hello!

I just wanted to know How can I set a pokemon as favorite? I can get if it is favorite with `$pokemon->getFavorite()` but I don't seem to make `$pokemon->setFavorite()` work.

Thanks!

**Comment by Gandaflux** [comment]
you will be able with #81

**Comment by NicklasWallgren** [comment]
Resolved
