### ISSUE TITLE
 'Please check your environment configuration. The log directory is not writable.'

### ISSUE THREAD

**Issue by sensityy** [NicklasWallgren/PokemonGoAPI-PHP#9]
Hey, I get this everytime I try to run a file, any suggestions?

https://gyazo.com/e56ab03acbd6aa9cb2acbbb50bf317f3

Thanks in advance.

**Comment by tomHash** [comment]
when you start the project and make a copy of `.env.example` to `.env`, it has a `LOG_FILE_PATH` which needs setting to an absolute file location. If this is already set then the directory that files in needs to be made writeable

**Comment by NicklasWallgren** [comment]
Thanks for the clarification @tomHash. This shouldn't be a problem in the latest release.
