### ISSUE TITLE
[Suggestion] Pokemon canUpgrade

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#99]
I saw in "PokemonDetailsTrait.php" there's a method "canEvolve()" I can call before call $pokemon->evolve();

Can you add a similar method "canUpgrade()" to check if a Pokeon can be upgraded (candy and dust required matches) ?

**Comment by NicklasWallgren** [comment]
https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/a54e08ba1da5583f34ea0e36f9e643ad8805501a

**Comment by NicklasWallgren** [comment]
Resolved
